# Application Settings
application:
  address: notset
  clientKey: notset
  clientSecret: notset
  accesstoken: notset

# Post Settings
post:
  start: true
  stop: true
  restart: true
  visibility: public
  prefix: "[MstdnStatus]"
  includetime: true
  dateformat: "yyyy/MM/dd HH:mm:ss"

# Language Settings
language: jp